# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98175c757fcbf056240e7df06f9cffbadd769fd7e477d0cd53a1bf7842a2db10b077956186c4407007f55899ca9ce2b0a0a7c72d624f7887ca86823925de4311

test:
  secret_key_base: e95f1aa0b3820be89a5da5f950baf31bcf86c22768f6e5b9cc787d47f0388f0ecad6e1c4f79cf5301bcff119228c967b4cd79c109e64b71c6d1e10024a519e9c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
